name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    # It includes docker runtime
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockerfile:
          - ./Dockerfile
          - ./Docker-basicpoller
        image_name:
          - rkthumuluri007/agent
          - rkthumuluri007/basicagent

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ matrix.image_name }}:2.2.2
