name: Build and Push Docker Images

on:
  push:
    branches:
      - main  # Change to your branch if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image 1
        run: |
          docker build -f Dockerfile -t rkthumuluri007/agent:latest .
          docker push rkthumuluri007/agent:latest

      - name: Build and push image 2
        run: |
          docker build -f Docker-basicpoller -t rkthumuluri007/basicagent:latest .
          docker push rkthumuluri007/basicagent:latest
